#!/usr/bin/env python3
"""Convert toasters_and_toast.png sprite sheet to RGB332 + alpha mask C header.

Layout (321x97, background #111111):
  5 columns of 64px (1px gap between):
    Col 0 (x=0-63):  toaster frame 0 (rows 0-57) + toast (rows 59-96)
    Col 1 (x=64-127): toaster frame 1
    Col 2 (x=128-191): toaster frame 2
    Col 3 (x=192-255): toaster frame 3
    Col 4 (x=256-319): toaster frame 4

Output: src/toaster_sprites.h with PROGMEM arrays.
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow required. Install with: pip install Pillow")
    sys.exit(1)

BG_THRESHOLD = 30  # pixels with R+G+B <= this are background


def rgb332(r, g, b):
    """Convert 8-bit RGB to RGB332."""
    return (r & 0xE0) | ((g >> 3) & 0x1C) | (b >> 6)


def trim_bbox(img, x0, y0, x1, y1):
    """Trim a region to its tight content bounding box (exclude background)."""
    pixels = img.load()
    min_x, max_x = x1, x0
    min_y, max_y = y1, y0
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            r, g, b = pixels[x, y][:3]
            if r + g + b > BG_THRESHOLD:
                min_x = min(min_x, x)
                max_x = max(max_x, x)
                min_y = min(min_y, y)
                max_y = max(max_y, y)
    if min_x > max_x:
        return None
    return (min_x, min_y, max_x - min_x + 1, max_y - min_y + 1)


def convert_sprite(img, bbox):
    """Convert a sprite region to RGB332 data + packed alpha mask."""
    x, y, w, h = bbox
    pixels = img.load()

    rgb332_data = []
    alpha_bits = []

    for py in range(y, y + h):
        for px in range(x, x + w):
            r, g, b = pixels[px, py][:3]
            opaque = (r + g + b) > BG_THRESHOLD

            if opaque:
                rgb332_data.append(rgb332(r, g, b))
                alpha_bits.append(1)
            else:
                rgb332_data.append(0)
                alpha_bits.append(0)

    # Pack alpha bits into bytes (MSB first)
    alpha_packed = []
    for i in range(0, len(alpha_bits), 8):
        byte_val = 0
        for bit in range(8):
            if i + bit < len(alpha_bits) and alpha_bits[i + bit]:
                byte_val |= (0x80 >> bit)
        alpha_packed.append(byte_val)

    return rgb332_data, alpha_packed


def format_array(data, name, per_line=16):
    """Format a byte array as a PROGMEM C array."""
    lines = [f"static const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if i + per_line < len(data) else ""
        lines.append(f"  {hex_vals}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main():
    src_path = Path(r"C:\Users\sean\Desktop\toasters_and_toast.png")
    out_path = Path(r"C:\Users\sean\git_repos\cores3se-arduino\src\toaster_sprites.h")

    if not src_path.exists():
        print(f"ERROR: Source image not found: {src_path}")
        sys.exit(1)

    print(f"Loading {src_path}...")
    img = Image.open(src_path).convert("RGBA")
    print(f"Image size: {img.size[0]}x{img.size[1]}")

    # Define regions based on known layout
    col_width = 64
    regions = []

    # 5 toaster frames
    for i in range(5):
        x0 = i * col_width
        x1 = x0 + col_width - 1
        if i == 0:
            # First column: toaster is top half only (rows 0-57)
            regions.append(("toaster", x0, 0, x1, 57))
        else:
            regions.append(("toaster", x0, 0, x1, 60))

    # Toast: first column, bottom half (rows 59-96)
    regions.append(("toast", 0, 59, 63, 96))

    # Trim each region and convert
    sprites = []
    for label, x0, y0, x1, y1 in regions:
        bbox = trim_bbox(img, x0, y0, x1, y1)
        if bbox is None:
            print(f"WARNING: No content found for {label} at ({x0},{y0})-({x1},{y1})")
            continue
        sprites.append((label, bbox))
        x, y, w, h = bbox
        print(f"  {label}: {w}x{h} at ({x},{y})")

    toasters = [(l, b) for l, b in sprites if l == "toaster"]
    toasts = [(l, b) for l, b in sprites if l == "toast"]

    # Make all toaster frames the same size (max dimensions, centered)
    max_tw = max(b[2] for _, b in toasters)
    max_th = max(b[3] for _, b in toasters)
    print(f"\nNormalizing toaster frames to {max_tw}x{max_th}")

    # Generate header
    header_lines = [
        "#pragma once",
        "// Auto-generated by convert_sprites.py -- do not edit",
        "// Source: toasters_and_toast.png",
        "",
        "#include <Arduino.h>",
        "",
        "struct SpriteFrame {",
        "  uint8_t w;",
        "  uint8_t h;",
        "  const uint8_t* rgb332;",
        "  const uint8_t* alpha;",
        "};",
        "",
    ]

    # Convert toaster frames (use original tight bbox, not padded)
    toaster_names = []
    for i, (label, bbox) in enumerate(toasters):
        rgb_data, alpha_data = convert_sprite(img, bbox)
        rgb_name = f"sprite_toaster{i}_rgb"
        alpha_name = f"sprite_toaster{i}_alpha"
        w, h = bbox[2], bbox[3]
        toaster_names.append((w, h, rgb_name, alpha_name))

        header_lines.append(f"// Toaster frame {i} ({w}x{h})")
        header_lines.append(format_array(rgb_data, rgb_name))
        header_lines.append("")
        header_lines.append(format_array(alpha_data, alpha_name))
        header_lines.append("")

    # Convert toast
    toast_info = None
    if toasts:
        _, bbox = toasts[0]
        rgb_data, alpha_data = convert_sprite(img, bbox)
        w, h = bbox[2], bbox[3]
        toast_info = (w, h)

        header_lines.append(f"// Toast ({w}x{h})")
        header_lines.append(format_array(rgb_data, "sprite_toast_rgb"))
        header_lines.append("")
        header_lines.append(format_array(alpha_data, "sprite_toast_alpha"))
        header_lines.append("")

    # Frame index arrays
    header_lines.append(f"#define NUM_TOASTER_FRAMES {len(toaster_names)}")
    header_lines.append("")
    header_lines.append("static const SpriteFrame toasterFrames[NUM_TOASTER_FRAMES] PROGMEM = {")
    for w, h, rgb_name, alpha_name in toaster_names:
        header_lines.append(f"  {{ {w}, {h}, {rgb_name}, {alpha_name} }},")
    header_lines.append("};")
    header_lines.append("")

    if toast_info:
        w, h = toast_info
        header_lines.append(f"static const SpriteFrame toastFrame PROGMEM = {{ {w}, {h}, sprite_toast_rgb, sprite_toast_alpha }};")
    header_lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header_lines), encoding="utf-8")

    total_rgb = sum(b[2] * b[3] for _, b in sprites)
    total_alpha = sum((b[2] * b[3] + 7) // 8 for _, b in sprites)
    print(f"\nGenerated {out_path}")
    print(f"Total PROGMEM: ~{total_rgb + total_alpha} bytes ({total_rgb} rgb + {total_alpha} alpha)")


if __name__ == "__main__":
    main()
