#!/usr/bin/env python3
"""Convert dvdlogo.png to a 1-bit alpha mask C header for runtime colorization.

The logo is blue on white/transparent. We scale it down to ~80px wide,
then store just the alpha mask (1 bit per pixel, packed). The bouncing
logo code colorizes it at runtime so it can change color on each bounce.
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow required. Install with: pip install Pillow")
    sys.exit(1)


def main():
    src_path = Path(r"C:\Users\sean\Desktop\dvdlogo.png")
    out_path = Path(r"C:\Users\sean\git_repos\cores3se-arduino\src\dvd_logo.h")

    img = Image.open(src_path).convert("RGBA")
    print(f"Original: {img.size[0]}x{img.size[1]}")

    # Scale to ~80px wide, maintaining aspect ratio
    target_w = 80
    aspect = img.size[1] / img.size[0]
    target_h = int(target_w * aspect)
    img = img.resize((target_w, target_h), Image.LANCZOS)
    print(f"Scaled: {target_w}x{target_h}")

    pixels = img.load()

    # Detect logo pixels: non-white and non-transparent
    # The logo is blue, background is white
    alpha_bits = []
    for y in range(target_h):
        for x in range(target_w):
            r, g, b, a = pixels[x, y]
            # White or transparent = background
            is_logo = a > 128 and (r + g + b) < 700
            alpha_bits.append(1 if is_logo else 0)

    # Pack into bytes (MSB first)
    alpha_packed = []
    for i in range(0, len(alpha_bits), 8):
        byte_val = 0
        for bit in range(8):
            if i + bit < len(alpha_bits) and alpha_bits[i + bit]:
                byte_val |= (0x80 >> bit)
        alpha_packed.append(byte_val)

    # Format as C header
    lines = [
        "#pragma once",
        "// Auto-generated by convert_dvd_logo.py -- do not edit",
        "// 1-bit alpha mask, colorized at runtime",
        "",
        "#include <Arduino.h>",
        "",
        f"#define DVD_LOGO_W {target_w}",
        f"#define DVD_LOGO_H {target_h}",
        "",
        "static const uint8_t dvdLogoAlpha[] PROGMEM = {",
    ]

    per_line = 16
    for i in range(0, len(alpha_packed), per_line):
        chunk = alpha_packed[i:i + per_line]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if i + per_line < len(alpha_packed) else ""
        lines.append(f"  {hex_vals}{comma}")

    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path}")
    print(f"Alpha mask: {len(alpha_packed)} bytes PROGMEM")
    print(f"Logo pixel count: {sum(alpha_bits)} of {target_w * target_h}")


if __name__ == "__main__":
    main()
